sudo: required
dist: trusty
group: deprecated-2017Q4

language: go

services:
  - docker

addons:
  postgresql: "9.6"

go:
  - "1.16"

before_install:
  - ./script/check_formatting.sh

install:
  - make setup

script:
  - make build
  - make test
  - make test-all
  - make docker-release
